### ISSUE TITLE
Creación de naves grandes

### ISSUE THREAD

**Issue by mimogollon1** [mimogollon1/coleccion-de-aviones#2]
**Creación de naves modelos**

Se deben hacer modelos las naves mas grandes que cumplan con la características

- [ ] Creación de naves Grandes

tempo estimado 5

**Comment by cristian1297** [comment]
![whatsapp image 2017-09-13 at 9 05 54 pm](https://user-images.githubusercontent.com/12750058/30409006-f4a68086-98c7-11e7-8cdc-d77d4605a704.jpeg)

Se hizo la creacion de naves grandes
