### ISSUE TITLE
Creación de naves pequeñas

### ISSUE THREAD

**Issue by mimogollon1** [mimogollon1/coleccion-de-aviones#4]
**Creación de naves pequeñas**

Se deben hacer modelos las naves mas grandes que cumplan con la características

- [x] Creación de naves pequeñas

tempo estimado 5

**Comment by yegonzalez23** [comment]
Se realiza la creacion de las naves pequeñas

**Comment by mimogollon1** [comment]
![19e2ed4a-1e9d-4041-8242-616a6284766b](https://user-images.githubusercontent.com/31084088/30408971-be65fbaa-98c7-11e7-8d76-ec7378d2e0bd.jpeg)
