### ISSUE TITLE
Personalización de las naves grandes

### ISSUE THREAD

**Issue by mimogollon1** [mimogollon1/coleccion-de-aviones#5]
**dar un estilo a las naves grandes**

Con los estilos definidos se deben implementar en las naves grandes

- [x] Estilización de naves grandes

tiempo: 5

**Comment by mimogollon1** [comment]
![sss](https://user-images.githubusercontent.com/31084088/30409411-74029eb2-98ca-11e7-80db-5c7e1bb3138b.jpeg)
se realiza lapersonalizacion

**Comment by cristianlemusxD** [comment]
![whatsapp image 2017-09-13 at 9 24 45 pm](https://user-images.githubusercontent.com/13228437/30409367-41e5b270-98ca-11e7-8c7a-e2db89093e31.jpeg)
bocetos del avion grande con el diseño final de este
