### ISSUE TITLE
Personalización de naves medianas

### ISSUE THREAD

**Issue by mimogollon1** [mimogollon1/coleccion-de-aviones#6]
**dar un estilo a las naves medianas**

Con los estilos definidos se deben implementar en las naves medianas

- [ ] Estilización de naves medianas

tiempo: 5

**Comment by cristian1297** [comment]
![whatsapp image 2017-09-13 at 9 29 03 pm](https://user-images.githubusercontent.com/12750058/30409489-feec372c-98ca-11e7-8d3a-461f8e25256f.jpeg)

Se hace el diseño de las naves medianas
