### ISSUE TITLE
Personalización de las naves pequeñas

### ISSUE THREAD

**Issue by mimogollon1** [mimogollon1/coleccion-de-aviones#7]
**dar un estilo a las naves pequeñas**

Con los estilos definidos se deben implementar en las naves pequeñas

- [x] Estilización de naves pequeñas

tiempo: 5

**Comment by yegonzalez23** [comment]
Personalizacion de naves pequeñas completa

**Comment by mimogollon1** [comment]
![qqqq](https://user-images.githubusercontent.com/31084088/30409476-dda538de-98ca-11e7-9ed2-d2694df545fd.jpeg)
