### ISSUE TITLE
Material 

### ISSUE THREAD

**Issue by yegonzalez23** [mimogollon1/coleccion-de-aviones#9]
Material utilizado para realizar las naves
 -  [x] Adquisicion del papel
 -  [x] Corte del pael

**Comment by mimogollon1** [comment]
se realizan  los cortes del material
![baeafb14-df3d-40ed-9058-36823727f1bc 1](https://user-images.githubusercontent.com/31084088/30409043-317901f0-98c8-11e7-8abe-2828f444a3fe.jpeg)
